---
title: "sgeDM_TF_analysis"
author: "c ryan"
date: "3/22/2021"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(cowplot)
library(stringr)
library(metafolio)
library(parallel)
library(cobs)

workDir <- "~/Dropbox (Personal)/scRNA/SGE_DM/TFanalysis/"
figDir <- paste0(workDir,"figures/")

dir.create(figDir)


```



```{r data}

pData <- "~/Dropbox (Personal)/scRNA/SGE_DM/paulData/tfData/"

weightMat.c00.aggRec.LPS <- readRDS(paste0(pData,"weightmat_cluster_0_LPS_gc.overall.agg.rec.RDS"))
weightMat.c00.aggRec.NC <- readRDS(paste0(pData,"weightmat_cluster_0_NC_gc.overall.agg.rec.RDS"))
weightMat.c02.aggRec.LPS <- readRDS(paste0(pData,"weightmat_cluster_2_LPS_gc.overall.agg.rec.RDS"))
weightMat.c02.aggRec.NC <- readRDS(paste0(pData,"weightmat_cluster_2_NC_gc.overall.agg.rec.RDS"))

TFVS.c00.aggRec.LPS <- readRDS(paste0(pData,"TF_very_strong_links_reduced_celltype_CD8_A_at_LPS.RDS"))
TFVS.c00.aggRec.NC <- readRDS(paste0(pData,"TF_very_strong_links_reduced_celltype_CD8_A_at_NC.RDS"))
TFVS.c02.aggRec.LPS <- readRDS(paste0(pData,"TF_very_strong_links_reduced_celltype_NK_at_LPS.RDS"))
TFVS.c02.aggRec.NC <- readRDS(paste0(pData,"TF_very_strong_links_reduced_celltype_NK_at_NC.RDS"))

dmData <- "~/Dropbox (Personal)/scRNA/SGE_DM/regressGE/results/"

assign(x = paste0("res_full_aggRec_DMpbRegGE_c00"),
       value = read.table(paste0(dmData,"results_c00_agRec_emmreml")))
assign(x = paste0("res_full_aggRec_DMpbRegGE_c02"),
       value = read.table(paste0(dmData,"results_c02_agRec_emmreml")))

weightMat.c00.aggRec.LPS <- readRDS(paste0(pData,"weightmat_cluster_0_LPS_gc.overall.agg.rec.RDS"))
weightMat.c00.aggRec.NC <- readRDS(paste0(pData,"weightmat_cluster_0_NC_gc.overall.agg.rec.RDS"))
weightMat.c02.aggRec.LPS <- readRDS(paste0(pData,"weightmat_cluster_2_LPS_gc.overall.agg.rec.RDS"))
weightMat.c02.aggRec.NC <- readRDS(paste0(pData,"weightmat_cluster_2_NC_gc.overall.agg.rec.RDS"))


allTFlinks.c00.aggRec.LPS <- readRDS(paste0(pData,"links_celltype_CD8_A_at_LPS.RDS"))
allTFlinks.c00.aggRec.NC <- readRDS(paste0(pData,"links_celltype_CD8_A_at_NC.RDS"))
allTFlinks.c02.aggRec.LPS <- readRDS(paste0(pData,"links_celltype_NK_at_LPS.RDS"))
allTFlinks.c02.aggRec.NC <- readRDS(paste0(pData,"links_celltype_NK_at_NC.RDS"))


```


count the targets using str_count
```{r count targets}

TFVS.c00.aggRec.LPS$targetCount <- 0
TFVS.c00.aggRec.NC$targetCount <- 0
TFVS.c02.aggRec.LPS$targetCount <- 0
TFVS.c02.aggRec.NC$targetCount <- 0

for (t in 1:dim(TFVS.c00.aggRec.LPS)[1]) {
  TFVS.c00.aggRec.LPS$targetCount[t] <- str_count(string = TFVS.c00.aggRec.LPS$target[t], pattern = ",") + 1
}

for (t in 1:dim(TFVS.c00.aggRec.NC)[1]) {
  TFVS.c00.aggRec.NC$targetCount[t] <- str_count(string = TFVS.c00.aggRec.NC$target[t], pattern = ",") + 1
}

for (t in 1:dim(TFVS.c02.aggRec.LPS)[1]) {
  TFVS.c02.aggRec.LPS$targetCount[t] <- str_count(string = TFVS.c02.aggRec.LPS$target[t], pattern = ",") + 1
}

for (t in 1:dim(TFVS.c02.aggRec.NC)[1]) {
  TFVS.c02.aggRec.NC$targetCount[t] <- str_count(string = TFVS.c02.aggRec.NC$target[t], pattern = ",") + 1
}


#in weightMat only
TFVS.c00.aggRec.LPSinWM <- TFVS.c00.aggRec.LPS[TFVS.c00.aggRec.LPS$TF %in% rownames(weightMat.c00.aggRec.LPS),]
TFVS.c00.aggRec.NCinWM <- TFVS.c00.aggRec.NC[TFVS.c00.aggRec.NC$TF %in% rownames(weightMat.c00.aggRec.NC),]
TFVS.c02.aggRec.LPSinWM <- TFVS.c02.aggRec.LPS[TFVS.c02.aggRec.LPS$TF %in% rownames(weightMat.c02.aggRec.LPS),]
TFVS.c02.aggRec.NCinWM <- TFVS.c02.aggRec.NC[TFVS.c02.aggRec.NC$TF %in% rownames(weightMat.c02.aggRec.NC),]

```

```{r plot results}
nBins <- 100

lps00 <- ggplot(data = TFVS.c00.aggRec.LPS, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c00 - LPS - aggRec; n=",dim(TFVS.c00.aggRec.LPS)[1]))

nc00 <- ggplot(data = TFVS.c00.aggRec.NC, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c00 - NC - aggRec; n=",dim(TFVS.c00.aggRec.NC)[1]))

lps02 <- ggplot(data = TFVS.c02.aggRec.LPS, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c02 - LPS - aggRec; n=",dim(TFVS.c02.aggRec.LPS)[1]))

nc02 <- ggplot(data = TFVS.c02.aggRec.NC, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c02 - NC - aggRec; n=",dim(TFVS.c02.aggRec.NC)[1]))

plot_grid(lps00, nc00, lps02, nc02, ncol = 2)
ggsave(paste0(figDir,"geneTargets_per_TF_hist.png"))

#weightmat only

lps00 <- ggplot(data = TFVS.c00.aggRec.LPSinWM, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c00 - LPS - aggRec; n=",dim(TFVS.c00.aggRec.LPSinWM)[1]))

nc00 <- ggplot(data = TFVS.c00.aggRec.NCinWM, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c00 - NC - aggRec; n=",dim(TFVS.c00.aggRec.NCinWM)[1]))

lps02 <- ggplot(data = TFVS.c02.aggRec.LPSinWM, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c02 - LPS - aggRec; n=",dim(TFVS.c02.aggRec.LPSinWM)[1]))

nc02 <- ggplot(data = TFVS.c02.aggRec.NCinWM, aes(x = targetCount)) +
  geom_histogram(bins = nBins) + xlab("TF's Number of Gene Targets") +
  ggtitle(paste0("c02 - NC - aggRec; n=",dim(TFVS.c02.aggRec.NCinWM)[1]))

plot_grid(lps00, nc00, lps02, nc02, ncol = 2)
ggsave(paste0(figDir,"geneTargets_per_TF_weightMat_hist.png"))
rm(lps00,nc00,lps02,nc02)
```

```{r targets}

ggplot() +
  geom_histogram(aes(x = allTFlinks.c00.aggRec.LPS[1]$`77_06`$importance), alpha = .5, binwidth = 5) +
  geom_histogram(aes(x = allTFlinks.c00.aggRec.LPS[1]$`77_06`$importance[(allTFlinks.c00.aggRec.LPS[1]$`77_06`$target %in% rownames(res_full_aggRec_DMpbRegGE_c00))]), 
                 alpha = .5, fill = "red", binwidth = 5) + 
  scale_y_log10()


for (impThresh in c(0,1,2,5,10)) {

  #impThresh <- 1
  genesUsed <- allTFlinks.c00.aggRec.LPS[1]$`77_06`$target[allTFlinks.c00.aggRec.LPS[1]$`77_06`$importance > impThresh &
                                                             allTFlinks.c00.aggRec.LPS[1]$`77_06`$target %in% rownames(res_full_aggRec_DMpbRegGE_c00)]
  #tfUsed <- allTFlinks.c00.aggRec.LPS[1]$`77_06`$TF[allTFlinks.c00.aggRec.LPS[1]$`77_06`$importance > impThresh]
  tfUsed <- allTFlinks.c00.aggRec.LPS[1]$`77_06`$TF[allTFlinks.c00.aggRec.LPS[1]$`77_06`$importance > impThresh & 
                                                      allTFlinks.c00.aggRec.LPS[1]$`77_06`$target %in% rownames(res_full_aggRec_DMpbRegGE_c00)]
  tfLinks <- table(tfUsed)
  tfLinks <- tfLinks[tfLinks > 0]
  
  geneLinks <- unique(genesUsed)
  
  assign(x = paste0("tfLinks",impThresh), value = tfLinks)
  assign(x = paste0("geneLinks",impThresh), value = geneLinks)

}


length(genesUsed)
length(unique(genesUsed))
length(tfUsed)
length(unique(tfUsed))

tfplot1 <- ggplot() +
  #geom_histogram(aes(tfLinks0), binwidth = 25, alpha = .2) +
  geom_histogram(aes(x = tfLinks1), binwidth = 1, alpha = .8) +
  ggtitle(paste0("imp > 1, nTF=",length(tfLinks1),", nGene=",length(geneLinks1)))

tfplot2 <- ggplot() +
  #geom_histogram(aes(tfLinks0), binwidth = 25, alpha = .2) +
  geom_histogram(aes(x = tfLinks2), binwidth = 1, alpha = .8) +
  ggtitle(paste0("imp > 2, nTF=",length(tfLinks2),", nGene=",length(geneLinks2)))

tfplot5 <- ggplot() +
  #geom_histogram(aes(tfLinks0), binwidth = 25, alpha = .2) +
  geom_histogram(aes(x = tfLinks5), binwidth = 1, alpha = .8) +
  ggtitle(paste0("imp > 5, nTF=",length(tfLinks5),", nGene=",length(geneLinks5)))

tfplot10 <- ggplot() +
  #geom_histogram(aes(tfLinks0), binwidth = 25, alpha = .2) +
  geom_histogram(aes(x = tfLinks10), binwidth = 1, alpha = .8) +
  ggtitle(paste0("imp > 10, nTF=",length(tfLinks10),", nGene=",length(geneLinks10)))

plot_grid(tfplot1,tfplot2,tfplot5,tfplot10, ncol = 2)
ggsave(paste0(figDir,"gene_and_TFlinks_byImportance_samp7706_hist_dmFiltered.png"))

```

Which TF-target links to use?

```{r}

for (cluster in c("00","02")) {
  for (treatment in c("LPS","NC")) {
      
      cluster <- "00"
      variable <- "aggRec"
      treatment <- "LPS"
      
      if (variable == "aggRec") {
        secondVar <- "agRec"
      } else {
        secondVar <- variable
      }
      
      allLinks <- get(paste0("allTFlinks.c",cluster,".",variable,".",treatment))
      weightMatrix <- get(paste0("weightMat.c",cluster,".",variable,".",treatment))
      
      dmResults <- get(paste0("res_full_",variable,"_DMpbRegGE_c",cluster))
      
      betaColNum <- which(colnames(dmResults) == paste0("beta_trt",treatment,".",variable,"_cent"))
      sdevColNum <- which(colnames(dmResults) == paste0("sdev_trt",treatment,".",variable,"_cent"))
      pvalColNum <- which(colnames(dmResults) == paste0("p_value_trt",treatment,".",variable,"_cent"))
      fdrColNum <- which(colnames(dmResults) == paste0("fdr_",secondVar,"Nest",treatment))
      
      #set a threshold
      impThresh <- 1
      
      #for the first individual establish the dataframe
      indNum <- 1
      
      impBinary <- allLinks[indNum][[1]]$importance > impThresh
      
      indTF <- allLinks[indNum][[1]]$TF[impBinary]
      indTarget <- allLinks[indNum][[1]]$target[impBinary]
      
      threshTFTarget <- as.data.frame(paste0(indTF,"-",indTarget))
      colnames(threshTFTarget)[1] <- "tfTarget"
      
      threshTFTarget$TF <- indTF
      threshTFTarget$target <- indTarget
      threshTFTarget$count <- 1
      
      for (indNum in 2:45) {
        #then for each successive individual, get the same links
        #indNum <- 2
        print(indNum)
        impBinary <- allLinks[indNum][[1]]$importance > impThresh
        
        indTF <- allLinks[indNum][[1]]$TF[impBinary]
        indTarget <- allLinks[indNum][[1]]$target[impBinary]
        
        indThreshTFTarget <- paste0(indTF,"-",indTarget)
        
        #count matching links (add the T/F to the count column)
        threshTFTarget$count <- threshTFTarget$count + threshTFTarget$tfTarget %in% indThreshTFTarget
        
        #add new TF-Target links
        newLinksBinary <- !indThreshTFTarget %in% threshTFTarget$tfTarget
        
        threshTFTargetNEW <- as.data.frame(paste0(indTF[newLinksBinary],"-",indTarget[newLinksBinary]))
        colnames(threshTFTargetNEW)[1] <- "tfTarget"
        
        threshTFTargetNEW$TF <- indTF[newLinksBinary]
        threshTFTargetNEW$target <- indTarget[newLinksBinary]
        threshTFTargetNEW$count <- 1
        
        print(mean(indTF %in% threshTFTarget$TF))
        print(mean(indTarget %in% threshTFTarget$target))
        print(mean(indThreshTFTarget %in% threshTFTarget$tfTarget))
        
        threshTFTarget <- rbind(threshTFTarget,threshTFTargetNEW)
      }
      
      
      
      dim(threshTFTarget)
      
      tfIndThresh <- 5
      
      indThreshTFTarget <- subset(threshTFTarget, count >= tfIndThresh)
      
      ggplot() +
        geom_histogram(aes(x = indThreshTFTarget$count), binwidth = 1) +
        xlab("Number of Samples") +
        ggtitle(paste0("c",cluster," ",variable," ",treatment))
      
      ggsave(paste0(figDir,"Number_of_Samples_hist_c",cluster,"_",variable,"_",treatment,".png"))
      
      
      length(unique(indThreshTFTarget$TF))
      length(unique(indThreshTFTarget$target))
      sum(unique(indThreshTFTarget$target) %in% rownames(dmResults))
      dim(indThreshTFTarget)[1]
      
      dim(indThreshTFTarget)[1] / length(unique(indThreshTFTarget$target))
      
      ggplot() +
        geom_histogram(aes(x = table(indThreshTFTarget$TF)), binwidth = 1) +
        scale_y_log10()
      
      
      
      dim(indThreshTFTarget)
      
      #cut down to only tested targets
      geneTFresults <- indThreshTFTarget[indThreshTFTarget$target %in% rownames(dmResults),]
      
      #cut down to top TFs
      geneTFresults <- geneTFresults[geneTFresults$TF %in% rownames(weightMatrix),]
      
      
      geneTFresults$DMbeta <- 0
      geneTFresults$DMsdev <- 0
      geneTFresults$DMpval <- 0
      geneTFresults$DMfdr <- 0
      
      geneTFresults$TFslope <- 0
      geneTFresults$TFlog10p <- 0
      geneTFresults$TFtVal <- 0
      geneTFresults$TFse <- 0
      
      #for all the targets
      for (t in unique(geneTFresults$target)) {
        targetList <- which(geneTFresults$target == t)
        targetData <- which(rownames(dmResults) == t)
      
        #geneTFresults$DMlpsBeta[targetList] <- dmResults$beta_trtLPS.aggRec_cent[targetData]
        #geneTFresults$DMlpsSDev[targetList] <- dmResults$sdev_trtLPS.aggRec_cent[targetData]
        #geneTFresults$DMlpsPval[targetList] <- dmResults$p_value_trtLPS.aggRec_cent[targetData]
        #geneTFresults$DMlpsFDR[targetList] <- dmResults$fdr_agRecNestLPS[targetData]
        
        geneTFresults$DMbeta[targetList] <- dmResults[targetData, betaColNum]
        geneTFresults$DMsdev[targetList] <- dmResults[targetData, sdevColNum]
        geneTFresults$DMpval[targetList] <- dmResults[targetData, pvalColNum]
        geneTFresults$DMfdr[targetList] <- dmResults[targetData, fdrColNum]
      
      }
      
      
      #for all the TFs
      for (f in unique(geneTFresults$TF)) {
        tfList <- which(geneTFresults$TF == f)
        tfData <- which(rownames(weightMatrix) == f)
          
        geneTFresults$TFslope[tfList] <- weightMatrix$slope[tfData]
        geneTFresults$TFlog10p[tfList] <- weightMatrix$neglog10p[tfData]
        geneTFresults$TFtVal[tfList] <- weightMatrix$t.value[tfData]
        geneTFresults$TFse[tfList] <- weightMatrix$SE[tfData]
      }
      
      geneTFresults$sigDM <- geneTFresults$DMfdr < .1
      geneTFresults$sigTF <- geneTFresults$TFlog10p > 2
      geneTFresults$sigCOMB <- ifelse(geneTFresults$sigDM & geneTFresults$sigTF, "both",
                                      ifelse(geneTFresults$sigDM, "dm",
                                             ifelse(geneTFresults$sigTF, "tf", "neither")))
      
      ggplot(geneTFresults, aes(x = DMbeta, y = TFslope, col = sigCOMB)) +
        geom_point(alpha = .5)
      
      FET <- matrix(c(sum(geneTFresults$sigCOMB == "both"),
                        sum(geneTFresults$sigCOMB == "tf"),
                        sum(geneTFresults$sigCOMB == "dm"),
                        sum(geneTFresults$sigCOMB == "neither")), ncol = 2, byrow = T)
      
      FETresults <- fisher.test(FET)
      
      ggplot() +
        geom_histogram(aes(geneTFresults$TFlog10p))
      
      ggplot() +
        geom_histogram(aes(x = unlist(table(geneTFresults$TF)[table(geneTFresults$TF) > 0])), binwidth = 5) +
        scale_y_log10() +
        xlab("Number of Targets") +
        ggtitle(paste0("c",cluster," ",variable," ",treatment))
      
      ggsave(paste0(figDir,"Number_of_Targets_hist_c",cluster,"_",variable,"_",treatment,".png"))
      
      
      ### to do
      
      #standardize betas
      #standardize slopes?
      ggplot(data = geneTFresults, 
             aes(x = DMbeta / sqrt(DMsdev), 
                       y = TFslope / TFse)) +
        geom_point(aes(col = sigCOMB), alpha = .5) +
        xlab("DM Std Beta             (Higher Var in Higher AgRec ---------->)") +
        ylab("(<---------- Weaker TF in Higher AgRec)            TF Std Slope") +
        ggtitle("TF Beta v. DM Beta", 
                subtitle = paste0("c",cluster," ",variable," ",treatment,
                                  " | Fisher's Exact Test p=",round(FETresults$p.value,3),
                                                         ", OR=",round(FETresults$estimate,3)))
      
      ggsave(paste0(figDir,"TFbeta_v_DMbeta_xy_allTFs_c",cluster,"_",variable,"_",treatment,".png"))
      
      
      geneTFresultsSORT <- geneTFresults[order(geneTFresults$count),]
      ggplot(data = geneTFresultsSORT, 
             aes(x = DMbeta / sqrt(DMsdev), 
                       y = TFslope / TFse)) +
        geom_point(aes(col = count), alpha = 1) +
        xlab("DM Std Beta             (Higher Var in Higher AgRec ---------->)") +
        ylab("(<---------- Weaker TF in Higher AgRec)            TF Std Slope") +
        ggtitle("CD8A, LPS Condition", subtitle = paste0("Fisher's Exact Test p=",round(FETresults$p.value,3),
                                                         ", OR=",round(FETresults$estimate,3)))
      
      
      #combine for each unique TF
      uniqTF <- as.data.frame(unique(geneTFresults$TF))
      colnames(uniqTF) <- "TF"
      
      uniqTF$tval <- 0
      uniqTF$stdBetaMean <- 0
      uniqTF$stdBetaWeightMean <- 0
      uniqTF$nGenes <- 0
      uniqTF$avgCount <- 0
      uniqTF$propSig <- 0
      
      for (t in uniqTF$TF) {
        uNum <- which(uniqTF$TF == t)
        uGeneTFtmp <- subset(geneTFresults, TF == t)
        
        uniqTF$tval[uNum] <- uGeneTFtmp$TFtVal[1]
        uniqTF$stdBetaMean[uNum] <- mean(uGeneTFtmp$DMbeta / sqrt(uGeneTFtmp$DMsdev))
        uniqTF$stdBetaWeightMean[uNum] <- mean((uGeneTFtmp$DMbeta / sqrt(uGeneTFtmp$DMsdev)) * uGeneTFtmp$count)
        uniqTF$nGenes[uNum] <- dim(uGeneTFtmp)[1]
        uniqTF$propSig[uNum] <- mean(uGeneTFtmp$sigDM)
        uniqTF$avgCount[uNum] <- mean(uGeneTFtmp$count)
      
      }
      
      
      ggplot(uniqTF, aes(x = stdBetaMean, y = tval, col = log(nGenes))) +
        geom_point() +
        geom_smooth(method = "lm")
      
      ggplot(uniqTF, aes(x = stdBetaMean, y = nGenes)) +
        geom_point() +
        geom_smooth(method = "lm")
      
      ggplot(uniqTF, aes(x = tval, y = nGenes)) +
        geom_point() +
        geom_smooth(method = "lm")
      
      
      #combine for each unique target
      uniqTarget <- as.data.frame(unique(geneTFresults$target))
      colnames(uniqTarget) <- "target"
      
      uniqTarget$stdBeta <- 0
      uniqTarget$tvalMean <- 0
      #uniqTarget$tvalWeightMean <- 0
      uniqTarget$nTargets <- 0
      uniqTarget$avgCount <- 0
      uniqTarget$propSig <- 0
      
      for (t in uniqTarget$target) {
        uNum <- which(uniqTarget$target == t)
        uGeneTFtmp <- subset(geneTFresults, target == t)
        
        uniqTarget$stdBeta[uNum] <- (uGeneTFtmp$DMbeta / sqrt(uGeneTFtmp$DMsdev))[1]
        uniqTarget$tvalMean[uNum] <- mean(uGeneTFtmp$TFtVal)
        #uniqTarget$tvalWeightMean[uNum] <- mean((uGeneTFtmp$DMlpsBeta / sqrt(uGeneTFtmp$DMlpsSDev)) * uGeneTFtmp$count)
        uniqTarget$nTargets[uNum] <- dim(uGeneTFtmp)[1]
        uniqTarget$propSig[uNum] <- mean(uGeneTFtmp$sigTF)
        uniqTarget$avgCount[uNum] <- mean(uGeneTFtmp$count)
      
      }
      
      
      ggplot(uniqTarget, aes(x = stdBeta, y = tvalMean, col = log(nTargets))) +
        geom_point() +
        geom_smooth(method = "lm")
      
      
      
      #for each TF that passes the threshold - are the genes associated with it enriched for low pvalues?
      
      
      FDRcutoff <- .1
      
      uniqTF <- as.data.frame(unique(geneTFresults$TF))
      colnames(uniqTF) <- "TF"
      
      uniqTF$tval <- 0
      uniqTF$nGenes <- 0
      uniqTF$countSig <- 0
      uniqTF$otherGenes <- 0
      uniqTF$otherCountSig <- 0
      
      uniqTF$FETor <- 0
      uniqTF$FETpval <- 0
      uniqTF$FETsig <- FALSE
      
      
      for (t in uniqTF$TF) {
        #t <- "RAB2A"
        uNum <- which(uniqTF$TF == t)
        uGeneTFtmp <- subset(geneTFresults, TF == t)
        
        tfGeneList <- uGeneTFtmp$target
        
        uniqTF$tval[uNum] <- uGeneTFtmp$TFtVal[1]
        uniqTF$nGenes[uNum] <- dim(uGeneTFtmp)[1]
        
        
        tmpDMotherGenes <- dmResults[!rownames(dmResults) %in% tfGeneList,]
        tmpDMgenes <- dmResults[rownames(dmResults) %in% tfGeneList,]
        
        #MATCH the direction... is +tval enriched for +beta sig DM
        # if ( uniqTF$tval[uNum] < 0 ) {
        #   #if the TF slop is negative, we want to know if more +beta genes are sig than n.s.
        #   tmpDMotherGenes <- subset(tmpDMotherGenes, beta_trtLPS.aggRec_cent > 0)
        #   tmpDMgenes <- subset(tmpDMgenes, beta_trtLPS.aggRec_cent > 0)
        # } else {
        #   tmpDMotherGenes <- subset(tmpDMotherGenes, beta_trtLPS.aggRec_cent < 0)
        #   tmpDMgenes <- subset(tmpDMgenes, beta_trtLPS.aggRec_cent < 0)
        # }
        
        if (dim(tmpDMgenes)[1] > 0) {
        uniqTF$countSig[uNum] <- sum(tmpDMgenes$fdr_agRecNestLPS < FDRcutoff)
        uniqTF$otherCountSig[uNum] <- sum(tmpDMotherGenes$fdr_agRecNestLPS < FDRcutoff)
        
        uniqTF$nGenes[uNum] <- dim(tmpDMgenes)[1]
        uniqTF$otherGenes[uNum] <- dim(tmpDMotherGenes)[1]
        
        FET <- matrix(c(uniqTF$countSig[uNum],
                       uniqTF$otherCountSig[uNum],
                       uniqTF$nGenes[uNum],
                       uniqTF$otherGenes[uNum]), ncol = 2, byrow = T)
        
        FETresults <- fisher.test(FET)
        
        uniqTF$FETor[uNum] <- FETresults$estimate
        uniqTF$FETpval[uNum] <- FETresults$p.value
        
        } else {
          uniqTF$FETor[uNum] <- NA
          uniqTF$FETpval[uNum] <- NA
          uniqTF$FETsig[uNum] <- NA
        }
        
      }
      
      uniqTF$FETsig <- uniqTF$FETpval < 0.05
      
      
      ggplot(uniqTF, aes(x = tval, y = log(FETor), col = FETsig)) +
        geom_point() +
        xlab("(<---------- More Disreg in Higher AgRec)            TF Std Slope") +
        ylab("FET Odds Ratio (Enriched Sig Genes in TF -------------> )")
      
      ggplot(uniqTF, aes(x = tval, y = -log10(FETpval), col = FETsig)) +
        geom_point()
      
      
      ### Are targets and TF analysis correlated?
      ggplot(uniqTF, aes(x = nGenes, y = tval)) +
        geom_point(alpha = .5) +
        geom_smooth(method = "lm") +
        ggtitle("TF analysis StdBeta v. # of Targets",
                subtitle = paste0("c",cluster," ",variable," ",treatment))
      ggsave(paste0(figDir,"Targets_v_TFbeta_xy_allTFs_c",cluster,"_",variable,"_",treatment,".png"))
      
      ggplot(subset(uniqTF, nGenes > 9), aes(x = nGenes, y = tval)) +
        geom_point(alpha = .5) +
        geom_smooth(method = "lm") +
        ggtitle("TF analysis StdBeta v. # of Targets | >=10 target threshold", 
                subtitle = paste0("c",cluster," ",variable," ",treatment))
      ggsave(paste0(figDir,"Targets_v_TFbeta_xy_top10TFs_c",cluster,"_",variable,"_",treatment,".png"))
      
      ### Are targets and number of samples correlated?
      uniqTF$maxSamples <- 0
      uniqTF$meanSamples <- 0
      
      for (t in uniqTF$TF) {
        uNum <- which(uniqTF$TF == t)
         
        uniqTF$maxSamples[uNum] <- max(subset(geneTFresults, TF == t)$count)
        uniqTF$meanSamples[uNum] <- mean(subset(geneTFresults, TF == t)$count)
      
      }
      
      ggplot(uniqTF, aes(x = nGenes, y = maxSamples)) +
        geom_point(alpha = .5) +
        geom_smooth(method = "lm") +
        ggtitle("Max # of Samples v. # of Targets")
      
      ggplot(uniqTF, aes(x = nGenes, y = meanSamples)) +
        geom_point(alpha = .5) +
        geom_smooth(method = "lm") +
        ggtitle("Mean # of Samples v. # of Targets")
      
      geneTFresults$nTargets <- 0
      
      for (t in unique(geneTFresults$TF)) {
        uNum <- which(geneTFresults$TF == t)
        
         geneTFresults$nTargets[uNum] <- subset(uniqTF, TF == t)$nGenes
      }
      
      ggplot(geneTFresults, aes(x = nTargets, y = count)) +
        geom_point(alpha = .08) +
        #geom_smooth(method = "lm") +
        ggtitle("All Links: # of Samples v. # of Targets", 
                subtitle = paste0("c",cluster," ",variable," ",treatment))
      ggsave(paste0(figDir,"Samples_v_Targets_xy_allTFs_c",cluster,"_",variable,"_",treatment,".png"))
      
      
      
      
      #ggplot(subset(uniqTF, nGenes > 5), aes(x = nGenes, y = tval)) +
      #  geom_point(alpha = .5) +
      #  geom_smooth(method = "lm") +
      #  ggtitle("Mean # of Samples v. # of Targets", subtitle = ">5 target threshold")
      
      
      
      ### Permutation-based GSEA tests
      ### Originally developed by Jordan Anderson and Noah Snyder-Mackler. Modified by Tauras Vilgalys. 
      ### Last updated 2020 September 16
      
      ###outside R, build a csv file with geneName,hallmarkPathway
      
      # Parameter options on lines 11 and 12
      # Data and files to load on lines 16 and 30
      ## parameters to consider: 
      
      pvals <- FALSE ## are data in pvalues or betas? If betas, set pvals to FALSE
      weight <- 1 ## Weight to place on betas. Typically either a 1 or a 0, where 0 weights all effects equally.
              ## weight=0 acts like a KS test, and is typically used with pvalues.
      
      
          
        #cluster <- "00"
        #variable
        #treatment 
        #dir.create(paste0(workDir,"figures/gsea/c",cluster))
        
          #lmVar <- "trt" #can be trt or behav
          
          #starting with c00, treatment | res_full_aggRec_DMpb_c00
          #DMPBemmreml <- get(paste0("res_full_DMpb_c",cluster))
          #DMPBemmreml <- get(paste0("res_full_",variable,"_DMpbRegGE_c",cluster))
          DMPBemmreml <- dmResults
          
          #if we're dealing with treatment use col 2, behavior col 3
          sampleBetas <- as.data.frame(rownames(DMPBemmreml))
          
          if ( treatment == "LPS" ) {
            sampleBetas$Betas <- DMPBemmreml[,4]
          } else {
            sampleBetas$Betas <- DMPBemmreml[,3]
          }
      
          colnames(sampleBetas) <- c("Gene","Betas")
          
          ## get gene.list
          gene.list <- sampleBetas$Gene
          
          ## get nperm permutations of the vector of Betas
          nperm <- 1000
          for (i in 1:nperm) {
            tmpB <- sample(sampleBetas$Beta)
            cbind(sampleBetas,tmpB) -> sampleBetas; rm(tmpB)
          }; rm(i)#; head(sampleBetas)
          
          ## Get the list of gene sets to test. here the file starts with gene names and the associated GO terms. 
          
          ## i downloaded these hallmark gene sets from https://www.gsea-msigdb.org/gsea/msigdb/collections.jsp
          
          #gene.set <- read.table(paste0(workDir,"hallmark_genes/hallmarkPathways.csv"), sep = ",")
          gene.set <- geneTFresults[,c(3,2)]
          
          colnames(gene.set) <- c("Associated.Gene.Name","GO.Term.Accession")
          
          gene.set$gene_GO <- paste0(gene.set$Associated.Gene.Name,"_",gene.set$GO.Term.Accession)
          
          # Trim for expressed genes where B was estimated - only want gene set with emreml results
          gene.set2 <- subset(gene.set, gene.set$Associated.Gene.Name %in% sampleBetas$Gene)
          
          
          # Remove duplicated gene/GO pairings
          gene.set2 <- gene.set2[!duplicated(gene.set2$gene_GO),]
          
          ## Get list of gene ontologies to test, and the number of genes in each
          GO_res <- as.data.frame(matrix(ncol=2, nrow=length(unique(gene.set2$GO.Term.Accession)), unique(gene.set2$GO.Term.Accession)))
          GO_res$V2 <- 0
          GO_res <- GO_res[!(GO_res$V1 == ""),]; colnames(GO_res) <- c("GO", "n_genes")
          for (i in 1:nrow(GO_res)) {
            GO_res$n_genes[i] <- sum(gene.set2$GO.Term.Accession == GO_res$GO[i])
            }
          rm(i)
          GO_res$n_genes <- as.numeric(GO_res$n_genes)
          
          ## Only consider gene sets with at least 5 measured genes
          GO_res <- subset(GO_res, n_genes >= 10)
          
          ## Create a matrix of just the effect sizes, moving the gene names to the row.names
          effect_size_matrix<-sampleBetas[,-1]
          row.names(effect_size_matrix) <- sampleBetas[,1]
          
          
          ## GSEA function
          ### p-values are calculated based on a cdf. Another option would be to use a z-statistic, however that would assume normality? 
          GSEA=function(effect_size_matrix,gene_set_list,gene_GO_associations, weight=1,num.cores=NA,pvals=F){
            ## effect_size_matrix == gene x permutations matrix where rownames are the genes and the first column is the observed effect sizes (i.e., columns 2:ncol are the permuted betas)
            if (is.na(num.cores)) num.cores=detectCores()
            clus = makeCluster(getOption("cl.cores", num.cores))
            clusterExport(clus,varlist=ls(),envir=environment())
            a=parApply(clus,effect_size_matrix,2,function(tmp_data){
              names(tmp_data)=rownames(effect_size_matrix)
              tmp_data=sort(tmp_data,decreasing = T)
              correl.vector<-tmp_data
              tmp_all_genes<-names(tmp_data)
              #So that we ultimately weight on our betas when weight==1
              weighted.score.type=weight
              Reduce(rbind,lapply(gene_set_list,function(GOcat){
                tmp_set <- gene_GO_associations$Associated.Gene.Name[gene_GO_associations$GO.Term.Accession == GOcat]
                #First we're indexing what genes are or aren't in our gene set (1 vs 0)
                tag.indicator <- sign(match(tmp_all_genes, tmp_set, nomatch=0)) 
                no.tag.indicator <- 1 - tag.indicator 
                N <- length(tmp_all_genes) 
                Nh <- length(tmp_set) 
                Nm <-  N - Nh 
                #This is just if we want to do a KS test(maybe if we want to compare later to some of your results using GAGE); weight==0
                if (weight == 0) {
                  correl.vector <- rep(1, N)
                }
                alpha <- weighted.score.type
                if (pvals==T) {correl.vector=-log10(correl.vector)}
                correl.vector <- abs(correl.vector**alpha)
                #Normalizing our Incremental increase by the sum of the abs our "correlations" (sum.correl.tag) and 
                #normalizing our incremental decrease by the number of genes not in our set (Nm, which remember came from N-Nh above).
                sum.correl.tag  <- sum(correl.vector[which(tag.indicator == 1)])
                #attempting to remove the normalization
                norm.tag    <- 1.0 / sum.correl.tag
                norm.no.tag <- 1.0 / Nm
                #Then we just walk down the gene list adding or substracting as such
                ## don't use normalization in the math
                RES <- cumsum(tag.indicator * correl.vector * norm.tag - no.tag.indicator * norm.no.tag)
                #RES <- cumsum(tag.indicator * correl.vector - no.tag.indicator)
                #Then obviously this is for maximum positively vs negatively enriched 
                max.ES <- max(RES)
                min.ES <- min(RES)
                if (max.ES > - min.ES) {
                  #      ES <- max.ES
                  ES <- signif(max.ES, digits = 5)
                  arg.ES <- which.max(RES)
                } else {
                  #      ES <- min.ES
                  ES <- signif(min.ES, digits=5)
                  arg.ES <- which.min(RES)
                }
                #if (length(gene_set)==1) {plot(cumsum(tag.indicator * correl.vector * norm.tag - no.tag.indicator * norm.no.tag),type = "l",xlab="Gene Index",ylab="Running Enrichment Score",xaxt="n"); axis(1,at=tag.indicator*1:length(tag.indicator),labels=T,tick=T)}
                return(c(max.ES,min.ES))}))
            })
            ## Returns two columns, one for upreg and one for downreg
            a=data.frame(a)
            a_upreg=a[1:length(gene_set_list),]
            a_downreg=a[(length(gene_set_list)+1):nrow(a),]
            rownames(a_upreg)=names(gene_set_list)
            rownames(a_downreg)=names(gene_set_list)
            #rownames(a)=names(gene.set)
            ## This doesn't seem right. Why would the pvals be lower if the max doesn't exceed the null?
            pvals_upreg=apply(a_upreg,1,function(x){
              #signif((sum(x[1] >= x[2:length(x)])+1)/(length(x)), digits=5)
              ee <- ecdf(x[2:length(x)]); 1 - ee(x[1])
              })
            names(pvals_upreg)=names(gene_set_list)
            pvals_downreg=apply(a_downreg,1,function(x){
              #signif((sum(x[1] <= x[2:length(x)])+1)/(length(x)), digits=5)
              ee <- ecdf(x[2:length(x)]); ee(x[1])
              })
            names(pvals_downreg)=names(gene_set_list)
            pvals=cbind(pvals_upreg,pvals_downreg); 
            #colnames(pvals)=c("pval_upreg","pval_downreg")
            colnames(pvals)=c("pval_upVariance","pval_downVariance")
            output=list(a_upreg,a_downreg,pvals)
          }
          
          ## Run GSEA function for each GO term (defined earlier in GO_res$GO)
          output <- GSEA(effect_size_matrix = effect_size_matrix,
                       gene_set_list = unique(GO_res$GO),
                       gene_GO_associations = gene.set2,
                       weight = 1, pvals=F)
          
          names(output)=c("NES_matrix_upVariance","NES_matrix_downVariance","p_values")
          
          
          
          
          # Normalize + ES' by the mean of + ES values, and - ES' by the mean of - ES null values for that gene set. 
          ##This should effectively control for differences in gene set size
          pos.ES.norm<-matrix(0,nrow=nrow(GO_res),ncol=nperm+1)
          neg.ES.norm<-matrix(0,nrow=nrow(GO_res),ncol=nperm+1)
          for (i in 1:length(GO_res$GO)) {
                   pos.ES <- unlist(output$NES_matrix_upVariance[i,])
                   names(pos.ES)<-NULL
                   neg.ES <- unlist(output$NES_matrix_downVariance[i,])
                    names(neg.ES)<-NULL
                   #for a given gene set, N, calculate the mean of the positive max ES for estimated+ permuted ES.
                   #calculate the mean of the max negative ES for estimate+ permuted ES also
                   pos.m <- mean(pos.ES)
                   neg.m <- mean(abs(neg.ES))
                   #Then for each permutation in that geneset, scale ES by this mean value, depending on if it was max + or max - ES
                   for (j in 1:(nperm+1)){
                   pos.ES.norm[i,j]<-pos.ES[j]/pos.m
                   neg.ES.norm[i,j]<-neg.ES[j]/neg.m
                   }
          }
          # FDR? 
          ## Calculate p-values for one of the null distributions as well
          perm_upreg <- apply(output$NES_matrix_upVariance[,-1],1,function(x) {ee <- ecdf(x[2:length(x)]); 1 - ee(x[1])})
          perm_downreg <- apply(output$NES_matrix_downVariance[,-1],1,function(x) {ee <- ecdf(x[2:length(x)]); 1 - ee(x[1])})
          ## Use perm.fdr function (written by Joaquin Sanz, available from Snyder-Mackler et al. 2016: https://github.com/nsmackler/status_genome_2016/blob/master/perm_FDR.R)
          
          
          fdr_up <- perm.fdr(output$p_values, perm_upreg, "pval_upVariance", "fdr_vsPerm1")
          fdr_down <- perm.fdr(output$p_values, perm_upreg, "pval_downVariance", "fdr_vsPerm1")
          
          upregNES <- output$NES_matrix_upVariance[,1]
          dnregNES <- output$NES_matrix_downVariance[,1]
          
          
          cbind(as.character(GO_res$GO),output$p_values)
          
          #plot significant effects
          betasOnly <- as.data.frame(effect_size_matrix$Betas)
          colnames(betasOnly) <- c("betas")
          #rank where "1st rank" is most highly correlated
          betasOnly$rank <- rank(-betasOnly$betas)
          
          for (r in 1:2) {
            if(sum(output$p_values[,r] < .05) > 0) {
              for (g in which(output$p_values[,r] < .05)) {
                pathwayName <- as.character(GO_res$GO)[g]
                pathwayGenes <- subset(gene.set2, GO.Term.Accession == pathwayName)$Associated.Gene.Name
                betasOnly$pathway <- FALSE
                betasOnly$pathway <- rownames(effect_size_matrix) %in% pathwayGenes
                betasPathway <- subset(betasOnly, pathway)
                
                pValoutput <- output$p_values[g,r]
                
                if ( r == 1) {
                  NESoutput <- output$NES_matrix_upVariance[g,1]
                } else {
                  NESoutput <- output$NES_matrix_downVariance[g,1]
                }
                
                ggplot() +
                  geom_linerange(aes(x = betasOnly$rank, ymax = betasOnly$betas, ymin = 0), 
                                 alpha = 66/dim(effect_size_matrix)[1]) +
                  geom_linerange(aes(x = betasPathway$rank, ymax = betasPathway$betas, ymin = 0)) +
                  xlab("Rank") + ggtitle(pathwayName, 
                                         subtitle = paste0(subset(GO_res, GO == pathwayName)$n_genes," genes, ",
                                                           "p = ",round(as.numeric(pValoutput), digits = 3),
                                                           " NES = ",round(as.numeric(NESoutput), digits = 3),
                                                           "    ",colnames(output$p_values)[r]))
                ggsave(paste0(figDir,"gsea_stickPlot_c",cluster,"_",treatment,"_",pathwayName,".png"), width = 6, height = 4)
              }
            }
          }
          
          #gseaC00trtNC <- output
          #assign(x = paste0("gseaC",cluster,"by",lmVar), value = output)
          
          printOut <- as.data.frame(cbind(as.character(GO_res$GO),as.character(GO_res$n_genes),output$p_values,output$NES_matrix_upVariance[,1],output$NES_matrix_downVariance[,1]))
          
          colnames(printOut) <- c("pathway","nGenes","pval_upVar","pval_downVar","NES_upVar","NES_downVar")
          
          for ( c in 2:6) {
            printOut[,c] <- as.numeric(printOut[,c])
          }
          
          
          assign(x = paste0("gseaTFc",cluster,"by",variable,"by",treatment), value = printOut)
          
          
          
      #t <- "PKM"
      #t <- "BCL11B"
      
      ggplot(data = subset(geneTFresults, TF == t), 
             aes(x = DMbeta / sqrt(DMsdev), 
                       y = TFslope / TFse)) +
        geom_point(aes(col = sigCOMB), alpha = .5) +
        xlab("DM Std Beta             (Higher Var in Higher AgRec ---------->)") +
        ylab("(<---------- Weaker TF in Higher AgRec)            TF Std Slope") +
        ggtitle("TF Beta v. DM Beta | TFs w/ at Least 10 targets", 
                subtitle = paste0("c",cluster," ",variable," ",treatment))
      
      
      ###
      ### nope it is correct, need to swap for standardized betas though? ranks shouldn't change
      ###
      
      sigTFlist <- unique(subset(geneTFresults, sigTF & TFslope < 0 & nTargets > 9)$TF)
      
      uniqTF[uniqTF$TF %in% sigTFlist,]
      
      sigPrint <- printOut[printOut$pathway %in% sigTFlist,]
      
      sigPrint$dir <- ""
      sigPrint$pval <- 0
      sigPrint$NES <- 0
      
      for (s in sigPrint$pathway) {
        sNum <- which(sigPrint$pathway == s)
        
        if ( sigPrint$pval_upVar[sNum] < sigPrint$pval_downVar[sNum]) {
          sigPrint$dir[sNum] <- "upVar"
          sigPrint$pval[sNum] <- sigPrint$pval_upVar[sNum]
          sigPrint$NES[sNum] <- sigPrint$NES_upVar[sNum]
        } else {
          sigPrint$dir[sNum] <- "downVar"
          sigPrint$pval[sNum] <- sigPrint$pval_downVar[sNum]
          sigPrint$NES[sNum] <- sigPrint$NES_downVar[sNum]
        }
      }
      
      sigPrint <- sigPrint[order(-sigPrint$NES),]
      sigPrint$pathway <- factor(sigPrint$pathway, levels = sigPrint$pathway)
      
      
      ggplot(data = printOut[printOut$pathway %in% sigTFlist,]) +
        geom_point(aes(x = NES_upVar, y = pathway, col = pval_upVar < .05, size = nGenes)) +
        ggtitle("GSEA Results - Significant, Weak Network-High AgRec TF's",
                subtitle = paste0("Cluster ",cluster," ",treatment," Treatment")) +
        ylab("TF") + xlab("GSEA Enrichment Score - Increased DM")
      
      ggsave(paste0(figDir,"GSEA_results_sigTFs_upVar_c",cluster,"_",variable,"_",treatment,".png"))
      
      
      ggplot(data = printOut[printOut$pathway %in% sigTFlist,]) +
        geom_point(aes(x = NES_downVar, y = pathway, col = pval_downVar < .05, size = nGenes)) +
        ggtitle("GSEA Results - Significant, Weak Network-High AgRec TF's",
                subtitle = paste0("Cluster ",cluster," ",treatment," Treatment")) +
        ylab("TF") + xlab("GSEA Enrichment Score - Decreased DM")
      
      ggsave(paste0(figDir,"GSEA_results_sigTFs_downVar_c",cluster,"_",variable,"_",treatment,".png"))
      
      ggplot(data = sigPrint) +
        geom_point(aes(x = NES, y = pathway, col = pval < .05, size = nGenes)) +
        ggtitle("GSEA Results - Significant, Weak Network-High AgRec TF's",
                subtitle = paste0("Cluster ",cluster," ",treatment," Treatment")) +
        ylab("TF") + xlab("(lower DM)   GSEA Enrichment Score   (higher DM)")
      
      ggsave(paste0(figDir,"GSEA_results_sigTFs_c",cluster,"_",variable,"_",treatment,".png"))
  }
}


```



```{r}
gg5col <- gg_color_hue(5)
randInd <- sample(x = 1:45, size = 5)


ggplot() +
  geom_histogram(aes(allLinks[randInd[1]][[1]]$importance), alpha = .2, bins = 50) +
  geom_histogram(aes(allLinks[randInd[2]][[1]]$importance), alpha = .2, bins = 50) +
  geom_histogram(aes(allLinks[randInd[3]][[1]]$importance), alpha = .2, bins = 50) +
  geom_histogram(aes(allLinks[randInd[4]][[1]]$importance), alpha = .2, bins = 50) +
  geom_histogram(aes(allLinks[randInd[5]][[1]]$importance), alpha = .2, bins = 50) +
  geom_vline(xintercept = 0.2) +
  geom_vline(xintercept = 1) +
  geom_vline(xintercept = 2) +
  ggtitle("5 Individual Sample Importances", subtitle = "lines at .2, 1, and 2") +
  scale_x_log10() + xlab("Importances")

ggsave(paste0(figDir,"importance_hist_",cluster,"_",variable,"_",treatment,".png"))

```


